name: demo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  shared_preferences: 2.0.17
  easy_splash_screen: 1.0.4
  hexcolor: 3.0.1
  stylish_bottom_bar: 1.0.0
  dio: 4.0.6
  flutter_easyloading: 3.0.5
  get_storage: 2.0.3
  flutter_switch: 0.3.2
  back_button_interceptor: 6.0.2
  flutter_exit_app: 1.1.2
  font_awesome_flutter: 10.3.0
  email_validator: 2.1.17
  flutter_pw_validator: 1.5.0
  connectivity_plus: 3.0.3
  image_picker: 0.8.6+1
  path: 1.8.2
  path_provider: 2.0.12
  cached_network_image: 3.2.3
  cached_memory_image: 1.3.1
  photo_view: 0.14.0
  permission_handler: 10.2.0
  image_cropper: 3.0.1
  flutter_local_notifications: ^9.9.1
  intl: 0.18.0
  firebase_core: 2.5.0
  cloud_firestore: 4.3.2
  another_stepper: 1.2.0
  intl_phone_field: 3.1.0
  radio_group_v2: 1.0.2
  location_picker_flutter_map: 1.2.0
  checkbox_grouped: 1.8.1
  flutter_background_service: 2.4.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

